### ISSUE TITLE
Input `embeds` is not a valid Discord embeds error

### ISSUE THREAD

**Issue by juraj-hrivnak** [hugoalh/send-discord-webhook-ghaction#494]
### Describe

This set up produces an error even though it should not.
```yml
- name: Send Discord message
        uses: "hugoalh/send-discord-webhook-ghaction@5af9cbe30a2a19e7ce18853012ef55487c985954" # 6.0.2
        if: ${{ steps.info.outputs.diff != '' }}
        with:
          key: ${{ secrets.DISCORD_WEBHOOK_DEV }}
          username: "GitHub"
          avatar_url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
          content: |
            ${{ steps.info.outputs.diff }}
```

This is the error:

```bash
Run hugoalh/send-discord-webhook-ghaction@5af9cbe30a2a19e7ce18853012ef55487c985954
  with:
    key: ***
    username: GitHub
    avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
    content: ### Added - Better Line Break - File Director - JEI Area Fixer - MiniEffects-Legacy Extended Life - NeverEnoughAnimation - Weather, Storms & Tornadoes ### Removed - Better Formatting Code - Weather 2 - Remastered ### Updated - Alfheim Lighting Engine - Forgelin-Continuous - Future MC - GroovyScript - Inventory Bogo Sorter - MixinBooter - Mo' Creatures Extended - Pyrotech - Recurrent Complex - Red Core - Storage Drawers - Fixeroo - Zen Utils
  
    tts: false
    allowed_mentions_parse: roles,users,everyone
    wait: true
    truncate_enable: true
    truncate_ellipsis: ...
    truncate_position: end
Initialize.
Error: TypeError: Input `embeds` is not a valid Discord embeds!
TypeError: Input `embeds` is not a valid Discord embeds!
    at file:///home/runner/work/_actions/hugoalh/send-discord-webhook-ghaction/5af9cbe30a2a19e7ce18853012ef55487c985954/dist/main.js:68:19
    at file:///home/runner/work/_actions/hugoalh/send-discord-webhook-ghaction/5af9cbe30a2a19e7ce18853012ef55487c985954/dist/main.js:71:7
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

### Version

6.0.2

### Execution Environment

```yml
ubuntu-latest
```
